// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Ali Khan",
    email: "ali.khan@example.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03001234567",
    subjects: ["Basic Math", "Nursery Rhymes"],
    classes: ["Daycare A", "Preschool A"],
    address: "Street 5, G-11/3, Islamabad",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Ayesha Siddiqui",
    email: "ayesha.siddiqui@example.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03101234567",
    subjects: ["Phonics", "Storytelling"],
    classes: ["Daycare B", "Preschool B"],
    address: "Block 4, Gulshan-e-Iqbal, Karachi",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Ahmed Raza",
    email: "ahmed.raza@example.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03211234567",
    subjects: ["Drawing", "Arts and Crafts"],
    classes: ["Daycare C", "Preschool C"],
    address: "Street 3, Model Town, Lahore",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Fatima Noor",
    email: "fatima.noor@example.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03331234567",
    subjects: ["Urdu Alphabets", "Islamic Studies"],
    classes: ["Daycare A", "Preschool A"],
    address: "H-8, Islamabad",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Sara Tariq",
    email: "sara.tariq@example.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03441234567",
    subjects: ["English Alphabets", "Music and Movement"],
    classes: ["Daycare B", "Preschool B"],
    address: "Clifton, Karachi",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Bilal Hashmi",
    email: "bilal.hashmi@example.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03021234567",
    subjects: ["Physical Activities", "Storytelling"],
    classes: ["Daycare C", "Preschool C"],
    address: "Johar Town, Lahore",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Zara Ahmed",
    email: "zara.ahmed@example.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03551234567",
    subjects: ["Social Skills", "Interactive Play"],
    classes: ["Daycare A", "Preschool A"],
    address: "F-10, Islamabad",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Hassan Javed",
    email: "hassan.javed@example.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03171234567",
    subjects: ["Color Recognition", "Nursery Rhymes"],
    classes: ["Daycare B", "Preschool B"],
    address: "DHA Phase 6, Karachi",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Mariam Sheikh",
    email: "mariam.sheikh@example.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03361234567",
    subjects: ["Number Recognition", "Arts and Crafts"],
    classes: ["Daycare C", "Preschool C"],
    address: "PECHS, Karachi",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Usman Farooq",
    email: "usman.farooq@example.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03031234567",
    subjects: ["Basic Shapes", "Music and Movement"],
    classes: ["Daycare A", "Preschool A"],
    address: "Gulberg, Lahore",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "STU001",
    name: "Sara Ali",
    email: "sara.ali@school.pk",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03011234567",
    grade: "Daycare",
    class: "Group A",
    subjects: ["Playtime", "Storytelling", "Motor Skills"],
    address: "House 21, Shahbaz Colony, Gujrat, Pakistan",
  },
  {
    id: 2,
    studentId: "STU002",
    name: "Aliya Khan",
    email: "aliya.khan@school.pk",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03012345678",
    grade: "Nursery",
    class: "Group B",
    subjects: ["Alphabet Basics", "Numbers 1-10", "Rhymes"],
    address: "Flat 12, Fawara Chowk, Gujrat, Pakistan",
  },
  {
    id: 3,
    studentId: "STU003",
    name: "Omar Raza",
    email: "omar.raza@school.pk",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03015678901",
    grade: "Preschool",
    class: "Group C",
    subjects: ["Basic Writing", "Drawing", "Numbers 1-20"],
    address: "Street 7, Jalalpur Road, Gujrat, Pakistan",
  },
  {
    id: 4,
    studentId: "STU004",
    name: "Maya Ahmed",
    email: "maya.ahmed@school.pk",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03019876543",
    grade: "Daycare",
    class: "Group A",
    subjects: ["Playtime", "Music", "Storytelling"],
    address: "House 35, Satellite Town, Gujrat, Pakistan",
  },
  {
    id: 5,
    studentId: "STU005",
    name: "Zain Shah",
    email: "zain.shah@school.pk",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03012347689",
    grade: "Nursery",
    class: "Group B",
    subjects: ["Animal Sounds", "Shape Recognition", "Color Identification"],
    address: "House 20, Sargodha Road, Gujrat, Pakistan",
  },
  {
    id: 6,
    studentId: "STU006",
    name: "Kiran Iqbal",
    email: "kiran.iqbal@school.pk",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03016789012",
    grade: "Preschool",
    class: "Group C",
    subjects: ["Basic Writing", "Drawing", "Numbers 1-20"],
    address: "Street 15, Peoples Colony, Gujrat, Pakistan",
  },
  {
    id: 7,
    studentId: "STU007",
    name: "Rehan Mirza",
    email: "rehan.mirza@school.pk",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03011234589",
    grade: "Daycare",
    class: "Group A",
    subjects: ["Playtime", "Storytelling", "Motor Skills"],
    address: "House 45, Gujrat City, Pakistan",
  },
  {
    id: 8,
    studentId: "STU008",
    name: "Nida Fatima",
    email: "nida.fatima@school.pk",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03019876504",
    grade: "Nursery",
    class: "Group B",
    subjects: ["Alphabet Basics", "Rhymes", "Basic Drawing"],
    address: "House 50, Khayaban Colony, Gujrat, Pakistan",
  },
  {
    id: 9,
    studentId: "STU009",
    name: "Samir Tariq",
    email: "samir.tariq@school.pk",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03011234567",
    grade: "Preschool",
    class: "Group C",
    subjects: ["Basic Numbers", "Storytelling", "Music"],
    address: "House 22, Race Course Road, Gujrat, Pakistan",
  },
  {
    id: 10,
    studentId: "STU010",
    name: "Areeba Javed",
    email: "areeba.javed@school.pk",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03011234456",
    grade: "Daycare",
    class: "Group A",
    subjects: ["Playtime", "Motor Skills", "Storytelling"],
    address: "House 10, Gulberg Colony, Gujrat, Pakistan",
  }
];
export const parentsData = [
  {
    id: 1,
    name: "Ali Ahmed",
    students: ["Sara Ali"],
    email: "ali.ahmed@school.pk",
    phone: "03014567890",
    address: "House 21, Shahbaz Colony, Gujrat, Pakistan",
  },
  {
    id: 2,
    name: "Fatima Khan",
    students: ["Aliya Khan"],
    email: "fatima.khan@school.pk",
    phone: "03016789012",
    address: "Flat 12, Fawara Chowk, Gujrat, Pakistan",
  },
  {
    id: 3,
    name: "Raza Qureshi",
    students: ["Omar Raza"],
    email: "raza.qureshi@school.pk",
    phone: "03019876543",
    address: "Street 7, Jalalpur Road, Gujrat, Pakistan",
  },
  {
    id: 4,
    name: "Ahmed Tariq",
    students: ["Maya Ahmed"],
    email: "ahmed.tariq@school.pk",
    phone: "03012347689",
    address: "House 35, Satellite Town, Gujrat, Pakistan",
  },
  {
    id: 5,
    name: "Zara Shah",
    students: ["Zain Shah"],
    email: "zara.shah@school.pk",
    phone: "03015678901",
    address: "House 20, Sargodha Road, Gujrat, Pakistan",
  },
  {
    id: 6,
    name: "Iqbal Hassan",
    students: ["Kiran Iqbal"],
    email: "iqbal.hassan@school.pk",
    phone: "03011234589",
    address: "Street 15, Peoples Colony, Gujrat, Pakistan",
  },
  {
    id: 7,
    name: "Sana Mirza",
    students: ["Rehan Mirza"],
    email: "sana.mirza@school.pk",
    phone: "03019876504",
    address: "House 45, Gujrat City, Pakistan",
  },
  {
    id: 8,
    name: "Faisal Fatima",
    students: ["Nida Fatima"],
    email: "faisal.fatima@school.pk",
    phone: "03011234567",
    address: "House 50, Khayaban Colony, Gujrat, Pakistan",
  },
  {
    id: 9,
    name: "Tariq Ali",
    students: ["Samir Tariq"],
    email: "tariq.ali@school.pk",
    phone: "03011234504",
    address: "House 22, Race Course Road, Gujrat, Pakistan",
  },
  {
    id: 10,
    name: "Javed Akhtar",
    students: ["Areeba Javed"],
    email: "javed.akhtar@school.pk",
    phone: "03011234456",
    address: "House 10, Gulberg Colony, Gujrat, Pakistan",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Basic Math",
    teachers: ["Ali Khan"],
  },
  {
    id: 2,
    name: "Nursery Rhymes",
    teachers: ["Ali Khan", "Hassan Javed"],
  },
  {
    id: 3,
    name: "Phonics",
    teachers: ["Ayesha Siddiqui"],
  },
  {
    id: 4,
    name: "Storytelling",
    teachers: ["Ayesha Siddiqui", "Bilal Hashmi"],
  },
  {
    id: 5,
    name: "Drawing",
    teachers: ["Ahmed Raza"],
  },
  {
    id: 6,
    name: "Arts and Crafts",
    teachers: ["Ahmed Raza", "Mariam Sheikh"],
  },
  {
    id: 7,
    name: "Urdu Alphabets",
    teachers: ["Fatima Noor"],
  },
  {
    id: 8,
    name: "Islamic Studies",
    teachers: ["Fatima Noor"],
  },
  {
    id: 9,
    name: "English Alphabets",
    teachers: ["Sara Tariq"],
  },
  {
    id: 10,
    name: "Music and Movement",
    teachers: ["Sara Tariq", "Usman Farooq"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "Daycare A",
    capacity: 20,
    grade: "Daycare",
    supervisor: "Ali Khan",
  },
  {
    id: 2,
    name: "Daycare B",
    capacity: 22,
    grade: "Daycare",
    supervisor: "Ayesha Siddiqui",
  },
  {
    id: 3,
    name: "Daycare C",
    capacity: 20,
    grade: "Daycare",
    supervisor: "Ahmed Raza",
  },
  {
    id: 4,
    name: "Preschool A",
    capacity: 18,
    grade: "Preschool",
    supervisor: "Fatima Noor",
  },
  {
    id: 5,
    name: "Preschool B",
    capacity: 16,
    grade: "Preschool",
    supervisor: "Sara Tariq",
  },
  {
    id: 6,
    name: "Preschool C",
    capacity: 20,
    grade: "Preschool",
    supervisor: "Bilal Hashmi",
  },
  {
    id: 7,
    name: "Kindergarten A",
    capacity: 18,
    grade: "Kindergarten",
    supervisor: "Zara Ahmed",
  },
  {
    id: 8,
    name: "Kindergarten B",
    capacity: 22,
    grade: "Kindergarten",
    supervisor: "Hassan Javed",
  },
  {
    id: 9,
    name: "Kindergarten C",
    capacity: 18,
    grade: "Kindergarten",
    supervisor: "Mariam Sheikh",
  },
  {
    id: 10,
    name: "Kindergarten D",
    capacity: 20,
    grade: "Kindergarten",
    supervisor: "Usman Farooq",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Basic Counting",
    class: "Daycare A",
    teacher: "Ali Khan",
  },
  {
    id: 2,
    subject: "Color Identification",
    class: "Daycare B",
    teacher: "Ayesha Siddiqui",
  },
  {
    id: 3,
    subject: "Alphabet Recognition",
    class: "Daycare C",
    teacher: "Ahmed Raza",
  },
  {
    id: 4,
    subject: "Story Time",
    class: "Preschool A",
    teacher: "Fatima Noor",
  },
  {
    id: 5,
    subject: "Arts and Crafts",
    class: "Preschool B",
    teacher: "Sara Tariq",
  },
  {
    id: 6,
    subject: "Rhymes and Songs",
    class: "Preschool C",
    teacher: "Bilal Hashmi",
  },
  {
    id: 7,
    subject: "Basic Math",
    class: "Kindergarten A",
    teacher: "Zara Ahmed",
  },
  {
    id: 8,
    subject: "Reading Skills",
    class: "Kindergarten B",
    teacher: "Hassan Javed",
  },
  {
    id: 9,
    subject: "Introduction to Science",
    class: "Kindergarten C",
    teacher: "Mariam Sheikh",
  },
  {
    id: 10,
    subject: "Physical Education",
    class: "Kindergarten D",
    teacher: "Usman Farooq",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Basic Counting",
    class: "Daycare A",
    teacher: "Ali Khan",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "Color Identification",
    class: "Daycare B",
    teacher: "Ayesha Siddiqui",
    date: "2025-01-02",
  },
  {
    id: 3,
    subject: "Alphabet Recognition",
    class: "Daycare C",
    teacher: "Ahmed Raza",
    date: "2025-01-03",
  },
  {
    id: 4,
    subject: "Story Time",
    class: "Preschool A",
    teacher: "Fatima Noor",
    date: "2025-01-04",
  },
  {
    id: 5,
    subject: "Arts and Crafts",
    class: "Preschool B",
    teacher: "Sara Tariq",
    date: "2025-01-05",
  },
  {
    id: 6,
    subject: "Rhymes and Songs",
    class: "Preschool C",
    teacher: "Bilal Hashmi",
    date: "2025-01-06",
  },
  {
    id: 7,
    subject: "Basic Math",
    class: "Kindergarten A",
    teacher: "Zara Ahmed",
    date: "2025-01-07",
  },
  {
    id: 8,
    subject: "Reading Skills",
    class: "Kindergarten B",
    teacher: "Hassan Javed",
    date: "2025-01-08",
  },
  {
    id: 9,
    subject: "Introduction to Science",
    class: "Kindergarten C",
    teacher: "Mariam Sheikh",
    date: "2025-01-09",
  },
  {
    id: 10,
    subject: "Physical Education",
    class: "Kindergarten D",
    teacher: "Usman Farooq",
    date: "2025-01-10",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Basic Counting",
    class: "Daycare A",
    teacher: "Ali Khan",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "Color Identification",
    class: "Daycare B",
    teacher: "Ayesha Siddiqui",
    dueDate: "2025-01-02",
  },
  {
    id: 3,
    subject: "Alphabet Recognition",
    class: "Daycare C",
    teacher: "Ahmed Raza",
    dueDate: "2025-01-03",
  },
  {
    id: 4,
    subject: "Story Time",
    class: "Preschool A",
    teacher: "Fatima Noor",
    dueDate: "2025-01-04",
  },
  {
    id: 5,
    subject: "Arts and Crafts",
    class: "Preschool B",
    teacher: "Sara Tariq",
    dueDate: "2025-01-05",
  },
  {
    id: 6,
    subject: "Rhymes and Songs",
    class: "Preschool C",
    teacher: "Bilal Hashmi",
    dueDate: "2025-01-06",
  },
  {
    id: 7,
    subject: "Basic Math",
    class: "Kindergarten A",
    teacher: "Zara Ahmed",
    dueDate: "2025-01-07",
  },
  {
    id: 8,
    subject: "Reading Skills",
    class: "Kindergarten B",
    teacher: "Hassan Javed",
    dueDate: "2025-01-08",
  },
  {
    id: 9,
    subject: "Introduction to Science",
    class: "Kindergarten C",
    teacher: "Mariam Sheikh",
    dueDate: "2025-01-09",
  },
  {
    id: 10,
    subject: "Physical Education",
    class: "Kindergarten D",
    teacher: "Usman Farooq",
    dueDate: "2025-01-10",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Basic Counting",
    class: "Daycare A",
    teacher: "Ali Khan",
    student: "Ahmed Ali",
    date: "2025-01-01",
    type: "exam",
    score: 85,
  },
  {
    id: 2,
    subject: "Color Identification",
    class: "Daycare B",
    teacher: "Ayesha Siddiqui",
    student: "Fatima Noor",
    date: "2025-01-02",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Alphabet Recognition",
    class: "Daycare C",
    teacher: "Ahmed Raza",
    student: "Zara Tariq",
    date: "2025-01-03",
    type: "exam",
    score: 88,
  },
  {
    id: 4,
    subject: "Story Time",
    class: "Preschool A",
    teacher: "Fatima Noor",
    student: "Bilal Khan",
    date: "2025-01-04",
    type: "exam",
    score: 92,
  },
  {
    id: 5,
    subject: "Arts and Crafts",
    class: "Preschool B",
    teacher: "Sara Tariq",
    student: "Mariam Ahmed",
    date: "2025-01-05",
    type: "exam",
    score: 95,
  },
  {
    id: 6,
    subject: "Rhymes and Songs",
    class: "Preschool C",
    teacher: "Bilal Hashmi",
    student: "Usman Ali",
    date: "2025-01-06",
    type: "exam",
    score: 87,
  },
  {
    id: 7,
    subject: "Basic Math",
    class: "Kindergarten A",
    teacher: "Zara Ahmed",
    student: "Hassan Javed",
    date: "2025-01-07",
    type: "exam",
    score: 89,
  },
  {
    id: 8,
    subject: "Reading Skills",
    class: "Kindergarten B",
    teacher: "Hassan Javed",
    student: "Mariam Sheikh",
    date: "2025-01-08",
    type: "exam",
    score: 93,
  },
  {
    id: 9,
    subject: "Introduction to Science",
    class: "Kindergarten C",
    teacher: "Mariam Sheikh",
    student: "Ahmed Farooq",
    date: "2025-01-09",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Physical Education",
    class: "Kindergarten D",
    teacher: "Usman Farooq",
    student: "Fatima Tariq",
    date: "2025-01-10",
    type: "exam",
    score: 94,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "National Independence Day Celebration",
    class: "Daycare A",
    date: "2025-08-14",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Eid Festivities",
    class: "Preschool A",
    date: "2025-07-15",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Pakistan Day Parade",
    class: "Preschool B",
    date: "2025-03-23",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Cultural Heritage Exhibition",
    class: "Kindergarten A",
    date: "2025-05-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Spring Festival",
    class: "Kindergarten B",
    date: "2025-04-15",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magic Lantern Show",
    class: "Daycare B",
    date: "2025-06-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Winter Sports Fest",
    class: "Preschool C",
    date: "2025-12-05",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Pakistan Cultural Parade",
    class: "Kindergarten C",
    date: "2025-09-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art and Craft Fair",
    class: "Preschool D",
    date: "2025-10-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Gala",
    class: "Kindergarten D",
    date: "2025-11-20",
    startTime: "10:00",
    endTime: "11:00",
  },
];
export const announcementsData = [
  {
    id: 1,
    title: "About 1A Math Test",
    class: "1A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 5A Math Test",
    class: "5A",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 1B Math Test",
    class: "1B",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 2B Math Test",
    class: "2B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
];

export const calendarEvents = [
  {
    title: "Morning Circle Time",
    allDay: false,
    start: new Date(2024, 11, 16, 8, 0),
    end: new Date(2024, 11, 16, 8, 45),
  },
  {
    title: "Story Time",
    allDay: false,
    start: new Date(2024, 11, 16, 9, 0),
    end: new Date(2024, 11, 16, 9, 45),
  },
  {
    title: "Arts & Crafts",
    allDay: false,
    start: new Date(2024, 11, 16, 10, 0),
    end: new Date(2024, 11, 16, 10, 45),
  },
  {
    title: "Outdoor Play",
    allDay: false,
    start: new Date(2024, 11, 16, 11, 0),
    end: new Date(2024, 11, 16, 11, 45),
  },
  {
    title: "Snack Time",
    allDay: false,
    start: new Date(2024, 11, 16, 13, 0),
    end: new Date(2024, 11, 16, 13, 45),
  },
  {
    title: "Nap Time",
    allDay: false,
    start: new Date(2024, 11, 16, 14, 0),
    end: new Date(2024, 11, 16, 14, 45),
  },
  {
    title: "Morning Circle Time",
    allDay: false,
    start: new Date(2024, 11, 17, 8, 0),
    end: new Date(2024, 11, 17, 8, 45),
  },
  {
    title: "Story Time",
    allDay: false,
    start: new Date(2024, 11, 17, 9, 0),
    end: new Date(2024, 11, 17, 9, 45),
  },
  {
    title: "Arts & Crafts",
    allDay: false,
    start: new Date(2024, 11, 17, 10, 0),
    end: new Date(2024, 11, 17, 10, 45),
  },
  {
    title: "Outdoor Play",
    allDay: false,
    start: new Date(2024, 11, 17, 11, 0),
    end: new Date(2024, 11, 17, 11, 45),
  },
  {
    title: "Snack Time",
    allDay: false,
    start: new Date(2024, 11, 17, 13, 0),
    end: new Date(2024, 11, 17, 13, 45),
  },
  {
    title: "Nap Time",
    allDay: false,
    start: new Date(2024, 11, 17, 14, 0),
    end: new Date(2024, 11, 17, 14, 45),
  },
  {
    title: "Morning Circle Time",
    allDay: false,
    start: new Date(2024, 11, 18, 8, 0),
    end: new Date(2024, 11, 18, 8, 45),
  },
  {
    title: "Story Time",
    allDay: false,
    start: new Date(2024, 11, 18, 9, 0),
    end: new Date(2024, 11, 18, 9, 45),
  },
  {
    title: "Arts & Crafts",
    allDay: false,
    start: new Date(2024, 11, 18, 10, 0),
    end: new Date(2024, 11, 18, 10, 45),
  },
  {
    title: "Outdoor Play",
    allDay: false,
    start: new Date(2024, 11, 18, 11, 0),
    end: new Date(2024, 11, 18, 11, 45),
  },
  {
    title: "Snack Time",
    allDay: false,
    start: new Date(2024, 11, 18, 13, 0),
    end: new Date(2024, 11, 18, 13, 45),
  },
  {
    title: "Nap Time",
    allDay: false,
    start: new Date(2024, 11, 18, 14, 0),
    end: new Date(2024, 11, 18, 14, 45),
  },
  {
    title: "Morning Circle Time",
    allDay: false,
    start: new Date(2024, 11, 19, 8, 0),
    end: new Date(2024, 11, 19, 8, 45),
  },
  {
    title: "Story Time",
    allDay: false,
    start: new Date(2024, 11, 19, 9, 0),
    end: new Date(2024, 11, 19, 9, 45),
  },
  {
    title: "Arts & Crafts",
    allDay: false,
    start: new Date(2024, 11, 19, 10, 0),
    end: new Date(2024, 11, 19, 10, 45),
  },
  {
    title: "Outdoor Play",
    allDay: false,
    start: new Date(2024, 11, 19, 11, 0),
    end: new Date(2024, 11, 19, 11, 45),
  },
  {
    title: "Snack Time",
    allDay: false,
    start: new Date(2024, 11, 19, 13, 0),
    end: new Date(2024, 11, 19, 13, 45),
  },
  {
    title: "Nap Time",
    allDay: false,
    start: new Date(2024, 11, 19, 14, 0),
    end: new Date(2024, 11, 19, 14, 45),
  },
];